version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2-node 
      - image: circleci/postgres:13.3 
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: viewing_party_api_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:@localhost/viewing_party_api_test
    steps:
      - checkout
      - ruby/install-deps # Installs Ruby dependencies
      - run:
          name: Wait for Database
          command: dockerize -wait tcp://localhost:5432 -timeout 30s
      - run:
          name: Database Setup
          command: bundle exec rake db:create db:migrate db:seed
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec

workflows:
  build-and-test:
    jobs:
      - test
